### ISSUE TITLE
Import contacts from social media

### ISSUE THREAD

**Issue by cprghunter** [CSC-307-My-Contacts/my-contacts#31]
time = 4hrs

**Comment by ysunkara** [comment]
Probably don't want to do either Facebook or gmail since we have to register developer accounts and deal with authorization which is a lot of overhead and doesn't seem to be within scope for this issue.

1. https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
2. https://developers.google.com/contacts/v3/#formatted

**Comment by AlexMaclean** [comment]
Lets de-scope this for the current sprint. I don't think it add a whole lot of value and seems like a huge pain

**Comment by ysunkara** [comment]
Actual Time: 3 hrs for research and discussion about descoping
